apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aws-efs
  namespace: storagerent
  labels:
    app: test-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 6Ki
  storageClassName: aws-efs
  